name: Auto update

on:
  # TODO: uncomment to enable scheduled execution
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  auto-update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # https://github.com/actions/setup-node/issues/1255
          node-version: ^22.18.0
          cache: npm

      - name: Install dependencies
        # TODO: set the module name to be analyzed
        run: |
          npm ci --omit=dev
          npm install antd@latest

      - name: Build
        run: npm run build

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m "Automated build"
          git push
